# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Feasted' do

end

target 'FeastedTests' do

end

target 'FeastedUITests' do

end

