source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Feasted' do
    pod 'Alamofire', '~> 3.0'
    pod 'Google/SignIn'
    pod 'Google/Analytics'
    pod 'ObjectMapper', '~> 1.1'
    pod 'AlamofireObjectMapper', '~> 2.1'
end

target 'FeastedTests' do

end

target 'FeastedUITests' do

end

