source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Feasted' do
	pod 'Alamofire', '~> 3.0'
	pod 'Google/SignIn'
	pod 'Google/Analytics'
	pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end

target 'FeastedTests' do

end

target 'FeastedUITests' do

end

